name: Build Deployment
on:
  push:
    branches: master
jobs:

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
  
  deploy:
    name: SFTP Transfer
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Send Build
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: '${{ secrets.SSH_USERNAME }}'
          server: '${{ secrets.SSH_HOST }}'
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: '${{secrets.SFTP_LOCAL}}'
          remote_path: '${{secrets.SFTP_REMOTE}}'
          sftpArgs: '-o ConnectTimeout=5'