name: Build & Deploy

on:
  push:
    branches: [master]


jobs:
  ssh_connection:
    name: Before Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DO_ACCESS }}
      - name: Access droplet and Run Build
        run: | 
          doctl compute ssh ${{ secrets.DO_ID }}
          doctl compute ssh --ssh-command ${{secrets.DO_COMMAND}}
        
          
