name: Build & Deploy

on:
  push:
    branches: [master]

env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
  SSH_KNOWN_HOSTS: ${{secrets.SSH_HOST}}
  

jobs:
  before_deploy:
    name: Before Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Preparing SSH connection pt1
      run: |
        apt-get update -y && apt-get install rsync make -y
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        echo "Host *" >> ~/.ssh/config
        echo "    StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 400 ~/.ssh/config
  deploy:
    name: Deploy
    needs: before_deploy
    runs-on: ubuntu-latest
    steps:
    - name: Building Website
      run: echo "Website"
        
          
