name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  before_deploy:
    name: Before Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Preparing SSH connection pt1
      run: ls
    - name: Preparing SSH connection pt2
      run: pwd
  deploy:
    name: Deploy
    needs: before_deploy
    runs-on: ubuntu-latest
    steps:
    - name: Building Website
      run: echo "Website"
        
          
