name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  before_deploy:
    name: Before Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Preparing SSH connection
      run: |
        echo "Before Deployment"
        pwd
        ls 
  deploy:
    name: Deploy
    needs: before_deploy
    runs-on: ubuntu-latest
    steps:
    - name: Building Website
      run: |
        echo "Mid Deployment"
        
          
