name: Build  & Deploy
on:
  push:
    branches: master
jobs:

  build:
    name: Build and Send 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Send Build
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: '${{ secrets.SSH_USERNAME }}'
          server: '${{ secrets.SSH_HOST }}'
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: '${{secrets.SFTP_LOCAL}}'
          remote_path: '${{secrets.SFTP_REMOTE}}'
          sftpArgs: '-o ConnectTimeout=5'
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Connection and Replacement
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          rm -rf ${{secrets.DEPLOY_PATH}}
          mv ${{secrets.SFTP_REMOTE}} ${{secrets.DEPLOY_PATH}}


    