name: Build Deployment
on:
  push:
    branches: master
jobs:

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: ng build
  
  deploy:
    name: SFTP Transfer
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Send Build
      run: whoami